import { Shadows_Into_Light, Raleway, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CartProvider from "@/context/CartContext";
import { AuthProvider } from "@/context/AuthContext";

const shadowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadows-into-light",
  weight: "400",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const imbPlexSerif = IBM_Plex_Serif({
  variable: "--font-ibm-plex-serif",
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Interiors Deco Zen - Home Page",
  description: "Generated by create next app",
  icons: {
    icons: [
      {
        src: "/favicon.ico",
        sizes: "32x32",
        type: "image/png",
      },
    ],
  },
  authors: [{ name: "Franco Ezequiel Ursino" }],
  keywords: "comercio, mueble, muebles, silla, sillas, mesa, mesas, sillon, sillón, sofá, sofa, mesita, mesitas, sillones, cama, camas, respaldos, respaldos de cama, colección de muebles, reposeras, luces, iluminación, iluminacion, lámparas, lampara, lamparas, lamparas de techo, colgantes, lamparas colgantes, lamparas de pie, veladores, velador, deco, decoración, decoracion, decoraciones, maceta, planta, macetas, plantas, cuadro, cuadros, conjunto de cuadros, abstractos, cuadros abstractos, espejos, espejo, espejos grandes, espejos chicos, living, comedor, cocina, dormitorio, pieza, cuarto, interior, exterior, interiores modernos"
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${shadowsIntoLight.variable} ${raleway.variable} ${imbPlexSerif.variable} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}